// Package dnsconf renders an api.ConfigSpec into dnsdist.conf and the dnsjos Lua
// modules (SPEC §6.4). Output is byte-for-byte deterministic for the same input.
package dnsconf

import (
	"errors"
	"fmt"
	"net/netip"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/billyriantono/dnsjos/internal/shared/api"
)

const (
	DefaultBaseDir    = "/etc/dnsdist"
	DefaultCDBPath    = "/var/lib/dnsjos/blocklist/current.cdb"
	DefaultDnstapAddr = "127.0.0.1:6000"
	ConsoleAddr       = "127.0.0.1:5199"

	// Header starts every rendered file.
	Header = "-- generated by dnsjos, do not edit\n"
)

// Relative paths of the rendered files (under NodeRuntime.BaseDir).
const (
	FileConf     = "dnsdist.conf"
	FileBlocking = "dnsjos/blocking.lua"
	FileAbuse    = "dnsjos/abuse.lua"
	FileCGK      = "dnsjos/cgk.lua"
	// Owned by the agent's CGK prober, never rendered.
	FileCGKAliases = "dnsjos/cgk-aliases.txt"
	FileCGKRewrite = "dnsjos/cgk-rewrite.txt"
)

// Render returns every file for rt.BaseDir, keyed by path relative to it.
func Render(spec api.ConfigSpec, rt api.NodeRuntime) (map[string][]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}
	rt = withDefaults(rt)
	if rt.ConsoleKey == "" || rt.WebPassword == "" || rt.WebAPIKey == "" {
		return nil, errors.New("runtime: console_key, web_password and web_api_key are required")
	}
	if !path.IsAbs(rt.BaseDir) || !path.IsAbs(rt.CDBPath) {
		return nil, errors.New("runtime: base_dir and cdb_path must be absolute")
	}
	if _, err := addrPort(rt.DnstapAddr); err != nil {
		return nil, fmt.Errorf("runtime: dnstap_addr: %w", err)
	}

	files := map[string][]byte{}
	var c strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&c, format, a...) }
	c.WriteString(Header)

	if n := spec.Tuning.UDPBufferBytes; n > 0 {
		w("setUDPSocketBufferSizes(%d, %d)\n", n, n)
	}
	acl, err := prefixes(spec.ACL)
	if err != nil {
		return nil, fmt.Errorf("acl: %w", err)
	}
	w("setACL(%s)\n", luaList(acl))

	l := spec.Listen
	first := true
	if l.Do53.Enabled {
		for _, a := range l.Do53.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.do53: %w", err)
			}
			for range max(l.Do53.ReusePortListeners, 1) {
				fn := "addLocal"
				if first {
					fn, first = "setLocal", false
				}
				w("%s(%s, {reusePort = true})\n", fn, luaString(ap))
			}
		}
	}
	cert, key := luaString(l.TLS.CertFile), luaString(l.TLS.KeyFile)
	if l.DoH.Enabled {
		for _, a := range l.DoH.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.doh: %w", err)
			}
			w("addDOHLocal(%s, %s, %s, %s, {reusePort = true})\n", luaString(ap), cert, key, luaString(l.DoH.Path))
		}
	}
	if l.DoT.Enabled {
		for _, a := range l.DoT.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.dot: %w", err)
			}
			w("addTLSLocal(%s, %s, %s, {reusePort = true})\n", luaString(ap), cert, key)
		}
	}
	if n := spec.Tuning.TCPWorkers; n > 0 {
		w("setMaxTCPClientThreads(%d)\n", n)
	}

	w("\ncontrolSocket(%s)\nsetKey(%s)\nsetConsoleACL(%s)\n", luaString(ConsoleAddr), luaString(rt.ConsoleKey), luaString("127.0.0.1/32"))

	web, err := addrPort(spec.Webserver.Listen)
	if err != nil {
		return nil, fmt.Errorf("webserver.listen: %w", err)
	}
	webACL, err := prefixes(spec.Webserver.PrometheusACL)
	if err != nil {
		return nil, fmt.Errorf("webserver.prometheus_acl: %w", err)
	}
	// The agent reads stats over loopback; never lock it out.
	for _, lo := range []string{"127.0.0.1/32", "::1/128"} {
		if !slices.Contains(webACL, lo) {
			webACL = append(webACL, lo)
		}
	}
	w("webserver(%s)\nsetWebserverConfig({password = %s, apiKey = %s, acl = %s, statsRequireAuthentication = true})\n",
		luaString(web), luaString(rt.WebPassword), luaString(rt.WebAPIKey), luaString(strings.Join(webACL, ", ")))

	if ca := spec.Cache; ca.Enabled {
		w("\ngetPool(\"\"):setCache(newPacketCache(%d, {minTTL = %d, maxTTL = %d, staleTTL = %d}))\n",
			ca.MaxEntries, ca.MinTTL, ca.MaxTTL, ca.StaleTTL)
		if ca.StaleTTL > 0 {
			// Serve entries expired for up to stale_ttl seconds when every backend is down.
			w("setStaleCacheEntriesTTL(%d)\n", ca.StaleTTL)
		}
	}

	c.WriteString("\n")
	for _, s := range spec.Upstreams.Servers {
		ap, err := addrPort(s.Address)
		if err != nil {
			return nil, fmt.Errorf("upstreams: %w", err)
		}
		name := ""
		if s.Name != "" {
			name = "name = " + luaString(s.Name) + ", "
		}
		w("newServer({address = %s, %sweight = %d, order = %d, sockets = %d, checkInterval = %d, pool = \"\"})\n",
			luaString(ap), name, s.Weight, s.Order, s.Sockets, spec.Upstreams.HealthCheckIntervalS)
	}
	if !slices.Contains(api.Policies, spec.Upstreams.Policy) {
		return nil, fmt.Errorf("upstreams.policy: unknown %q", spec.Upstreams.Policy)
	}
	w("setServerPolicy(%s)\n", spec.Upstreams.Policy) // identifier from a fixed allowlist

	module := func(rel string, body []byte) {
		files[rel] = body
		w("dofile(%s)\n", luaString(path.Join(rt.BaseDir, rel)))
	}
	if spec.Blocking.Enabled || spec.Abuse.Enabled || spec.CGK.Enabled {
		c.WriteString("\n")
	}
	if spec.Blocking.Enabled {
		b, err := renderBlocking(spec.Blocking, rt)
		if err != nil {
			return nil, err
		}
		module(FileBlocking, b)
	}
	if spec.Abuse.Enabled {
		b, err := renderAbuse(spec.Abuse)
		if err != nil {
			return nil, err
		}
		module(FileAbuse, b)
	}
	if spec.CGK.Enabled {
		b, err := renderCGK(spec.CGK, rt)
		if err != nil {
			return nil, err
		}
		module(FileCGK, b)
	}
	if x := strings.TrimRight(spec.Tuning.ExtraLua, "\n"); strings.TrimSpace(x) != "" {
		w("\n-- BEGIN extra_lua (verbatim from the profile)\n%s\n-- END extra_lua\n", x)
	}
	files[FileConf] = []byte(c.String())
	return files, nil
}

func withDefaults(rt api.NodeRuntime) api.NodeRuntime {
	def := func(s *string, v string) {
		if *s == "" {
			*s = v
		}
	}
	def(&rt.BaseDir, DefaultBaseDir)
	def(&rt.CDBPath, DefaultCDBPath)
	def(&rt.DnstapAddr, DefaultDnstapAddr)
	def(&rt.Hostname, "dnsjos")
	rt.BaseDir = path.Clean(rt.BaseDir)
	return rt
}

// luaString quotes s as a Lua 5.1 string literal. Every byte outside printable ASCII
// becomes a 3-digit decimal escape, so no input can break out of the literal.
func luaString(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch ch := s[i]; {
		case ch == '"' || ch == '\\':
			b.WriteByte('\\')
			b.WriteByte(ch)
		case ch >= 0x20 && ch < 0x7f:
			b.WriteByte(ch)
		default:
			fmt.Fprintf(&b, "\\%03d", ch)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func luaList(items []string) string {
	q := make([]string, len(items))
	for i, s := range items {
		q[i] = luaString(s)
	}
	return "{" + strings.Join(q, ", ") + "}"
}

// addrPort normalises "ip:port" ("[::]:53" style for IPv6).
func addrPort(s string) (string, error) {
	ap, err := netip.ParseAddrPort(s)
	if err != nil || ap.Addr().Zone() != "" {
		return "", fmt.Errorf("%q is not ip:port", s)
	}
	return ap.String(), nil
}

// prefixes normalises CIDRs (host bits cleared); a bare address becomes /32 or /128.
func prefixes(list []string) ([]string, error) {
	out := make([]string, 0, len(list))
	for _, s := range list {
		p, err := netip.ParsePrefix(s)
		if err != nil {
			a, aerr := netip.ParseAddr(s)
			if aerr != nil || a.Zone() != "" {
				return nil, fmt.Errorf("%q is not a CIDR", s)
			}
			p = netip.PrefixFrom(a, a.BitLen())
		}
		out = append(out, p.Masked().String())
	}
	return out, nil
}

// dnsWire encodes a domain name in DNS wire format ("." is the root).
func dnsWire(name string) ([]byte, error) {
	name = strings.TrimSuffix(name, ".")
	var b []byte
	if name != "" {
		for _, l := range strings.Split(name, ".") {
			if l == "" || len(l) > 63 {
				return nil, fmt.Errorf("%q is not a domain name", name)
			}
			b = append(b, byte(len(l)))
			b = append(b, l...)
		}
	}
	if b = append(b, 0); len(b) > 255 {
		return nil, fmt.Errorf("%q is too long", name)
	}
	return b, nil
}

// soaWire encodes "mname rname serial refresh retry expire minimum" as SOA rdata.
func soaWire(soa string) ([]byte, error) {
	f := strings.Fields(soa)
	if len(f) != 7 {
		return nil, errors.New("blocking.soa: must be 'mname rname serial refresh retry expire minimum'")
	}
	var out []byte
	for _, n := range f[:2] {
		w, err := dnsWire(n)
		if err != nil {
			return nil, fmt.Errorf("blocking.soa: %w", err)
		}
		out = append(out, w...)
	}
	for _, n := range f[2:] {
		v, err := strconv.ParseUint(n, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("blocking.soa: %q is not a 32-bit number", n)
		}
		out = append(out, byte(v>>24), byte(v>>16), byte(v>>8), byte(v))
	}
	return out, nil
}

var secretRe = regexp.MustCompile(`((?:setKey\(|password = |apiKey = ))"(?:[^"\\]|\\.)*"`)

// Mask replaces the console key, webserver password and API key with asterisks.
const Mask = `"********"`

// MaskSecrets returns the files as text with every node secret masked (UI previews).
func MaskSecrets(files map[string][]byte) map[string]string {
	out := make(map[string]string, len(files))
	for k, v := range files {
		out[k] = secretRe.ReplaceAllString(string(v), "${1}"+Mask)
	}
	return out
}
