// Package dnsconf renders an api.ConfigSpec into dnsdist.conf and the dnsjos Lua
// modules (SPEC §6.4). Output is byte-for-byte deterministic for the same input.
package dnsconf

import (
	"cmp"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"net/netip"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"golang.org/x/crypto/scrypt"

	"github.com/billyriantono/dnsjos/internal/shared/api"
)

const (
	DefaultBaseDir    = "/etc/dnsdist"
	DefaultCDBPath    = "/var/lib/dnsjos/blocklist/current.cdb"
	DefaultDnstapAddr = "127.0.0.1:6000"
	ConsoleAddr       = "127.0.0.1:5199"

	// Header starts every rendered file.
	Header = "-- generated by dnsjos, do not edit\n"
)

// Relative paths of the rendered files (under NodeRuntime.BaseDir).
const (
	FileConf     = "dnsdist.conf"
	FileBlocking = "dnsjos/blocking.lua"
	FileAbuse    = "dnsjos/abuse.lua"
	FileCGK      = "dnsjos/cgk.lua"
	// Owned by the agent's CGK prober, never rendered.
	FileCGKAliases = "dnsjos/cgk-aliases.txt"
	FileCGKRewrite = "dnsjos/cgk-rewrite.txt"
	// Names the agent found broken through a CGK alias (SPEC §6.6), never rendered.
	FileCGKLearned = "dnsjos/cgk-learned-exclude.txt"
	// Owned by the agent's allowlist sync, never rendered.
	FileAllowDomains = "dnsjos/allowlist-domains.txt"
	FileAllowIPs     = "dnsjos/allowlist-ips.txt"
)

// Render returns every file for rt.BaseDir, keyed by path relative to it.
func Render(spec api.ConfigSpec, rt api.NodeRuntime) (map[string][]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}
	rt = withDefaults(rt)
	if rt.ConsoleKey == "" || rt.WebPassword == "" || rt.WebAPIKey == "" {
		return nil, errors.New("runtime: console_key, web_password and web_api_key are required")
	}
	if !path.IsAbs(rt.BaseDir) || !path.IsAbs(rt.CDBPath) {
		return nil, errors.New("runtime: base_dir and cdb_path must be absolute")
	}
	if _, err := addrPort(rt.DnstapAddr); err != nil {
		return nil, fmt.Errorf("runtime: dnstap_addr: %w", err)
	}

	files := map[string][]byte{}
	var c strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&c, format, a...) }
	c.WriteString(Header)

	if n := spec.Tuning.UDPBufferBytes; n > 0 {
		w("setUDPSocketBufferSizes(%d, %d)\n", n, n)
	}
	acl, err := prefixes(spec.ACL)
	if err != nil {
		return nil, fmt.Errorf("acl: %w", err)
	}
	w("setACL(%s)\n", luaList(acl))

	l := spec.Listen
	first := true
	if l.Do53.Enabled {
		for _, a := range l.Do53.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.do53: %w", err)
			}
			for range max(l.Do53.ReusePortListeners, 1) {
				fn := "addLocal"
				if first {
					fn, first = "setLocal", false
				}
				w("%s(%s, {reusePort = true})\n", fn, luaString(ap))
			}
		}
	}
	cert, key := luaString(l.TLS.CertFile), luaString(l.TLS.KeyFile)
	if l.DoH.Enabled {
		for _, a := range l.DoH.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.doh: %w", err)
			}
			w("addDOHLocal(%s, %s, %s, %s, {reusePort = true})\n", luaString(ap), cert, key, luaString(l.DoH.Path))
		}
	}
	if l.DoT.Enabled {
		for _, a := range l.DoT.Addresses {
			ap, err := addrPort(a)
			if err != nil {
				return nil, fmt.Errorf("listen.dot: %w", err)
			}
			w("addTLSLocal(%s, %s, %s, {reusePort = true})\n", luaString(ap), cert, key)
		}
	}
	if n := spec.Tuning.TCPWorkers; n > 0 {
		w("setMaxTCPClientThreads(%d)\n", n)
	}

	w("\ncontrolSocket(%s)\nsetKey(%s)\nsetConsoleACL(%s)\n", luaString(ConsoleAddr), luaString(rt.ConsoleKey), luaString("127.0.0.1/32"))

	web, err := addrPort(spec.Webserver.Listen)
	if err != nil {
		return nil, fmt.Errorf("webserver.listen: %w", err)
	}
	webACL, err := prefixes(spec.Webserver.PrometheusACL)
	if err != nil {
		return nil, fmt.Errorf("webserver.prometheus_acl: %w", err)
	}
	// The agent reads stats over loopback; never lock it out.
	for _, lo := range []string{"127.0.0.1/32", "::1/128"} {
		if !slices.Contains(webACL, lo) {
			webACL = append(webACL, lo)
		}
	}
	w("webserver(%s)\nsetWebserverConfig({password = %s, apiKey = %s, acl = %s, statsRequireAuthentication = true})\n",
		luaString(web), luaString(hashCredential(rt.WebPassword)), luaString(hashCredential(rt.WebAPIKey)),
		luaString(strings.Join(webACL, ", ")))

	if ca := spec.Cache; ca.Enabled {
		if ca.StaleTTL > 0 {
			// Serve entries expired for up to stale_ttl seconds when every backend is down.
			// keepStaleData stops the cleaner (every 60 s) from deleting expired entries while
			// the pool is down, without it only entries expired < 60 s ago survive. Stale
			// answers carry a TTL of at most 60 s so clients come back once upstreams recover.
			w("\ngetPool(\"\"):setCache(newPacketCache(%d, {minTTL = %d, maxTTL = %d, staleTTL = %d, keepStaleData = true}))\n",
				ca.MaxEntries, ca.MinTTL, ca.MaxTTL, min(ca.StaleTTL, 60))
			w("setStaleCacheEntriesTTL(%d)\n", ca.StaleTTL)
		} else {
			w("\ngetPool(\"\"):setCache(newPacketCache(%d, {minTTL = %d, maxTTL = %d}))\n", ca.MaxEntries, ca.MinTTL, ca.MaxTTL)
		}
	}

	c.WriteString("\n")
	for _, s := range spec.Upstreams.Servers {
		ap, err := addrPort(s.Address)
		if err != nil {
			return nil, fmt.Errorf("upstreams: %w", err)
		}
		name := ""
		if s.Name != "" {
			name = "name = " + luaString(s.Name) + ", "
		}
		w("newServer({address = %s, %sweight = %d, order = %d, sockets = %d, checkInterval = %d, pool = \"\"})\n",
			luaString(ap), name, s.Weight, s.Order, s.Sockets, spec.Upstreams.HealthCheckIntervalS)
	}
	if !slices.Contains(api.Policies, spec.Upstreams.Policy) {
		return nil, fmt.Errorf("upstreams.policy: unknown %q", spec.Upstreams.Policy)
	}
	if spec.Upstreams.Policy == api.PolicyLatencyAware {
		w(latencyPolicy, cmp.Or(spec.Upstreams.LatencyFloorMs, 20)*1000)
	} else {
		w("setServerPolicy(%s)\n", spec.Upstreams.Policy) // identifier from a fixed allowlist
	}

	module := func(rel string, body []byte) {
		files[rel] = body
		w("dofile(%s)\n", luaString(path.Join(rt.BaseDir, rel)))
	}
	if spec.Blocking.Enabled || spec.Abuse.Enabled || spec.CGK.Enabled {
		c.WriteString("\n")
	}
	if spec.Blocking.Enabled {
		b, err := renderBlocking(spec.Blocking, rt)
		if err != nil {
			return nil, err
		}
		module(FileBlocking, b)
	}
	if spec.Abuse.Enabled {
		b, err := renderAbuse(spec.Abuse)
		if err != nil {
			return nil, err
		}
		module(FileAbuse, b)
	}
	if spec.CGK.Enabled {
		b, err := renderCGK(spec.CGK, rt)
		if err != nil {
			return nil, err
		}
		module(FileCGK, b)
	}
	if an := spec.Analytics; an.Enabled {
		ap, err := addrPort(an.StreamAddr)
		if err != nil {
			return nil, fmt.Errorf("analytics.stream_addr: %w", err)
		}
		if blocked, _ := addrPort(rt.DnstapAddr); ap == blocked {
			return nil, fmt.Errorf("analytics.stream_addr: %s is the blocked-query dnstap stream", ap)
		}
		rule := "AllRule()"
		if an.SampleRate > 1 {
			rule = fmt.Sprintf("ProbaRule(1 / %d)", an.SampleRate)
		}
		w("\n-- Analytics: every answer (forwarded, cache hit, self-answered) to the agent.\nlocal analytics = newFrameStreamTcpLogger(%s)\n", luaString(ap))
		// Distinct names: dnsdist exports rule hits by name, duplicates break /metrics.
		for _, c := range [][2]string{{"addResponseAction", "response"}, {"addCacheHitResponseAction", "cachehit"}, {"addSelfAnsweredResponseAction", "self"}} {
			w("%s(%s, DnstapLogResponseAction(%s, analytics), {name = \"dnsjos-analytics-%s\"})\n", c[0], rule, luaString(rt.Hostname), c[1])
		}
	}
	if x := strings.TrimRight(spec.Tuning.ExtraLua, "\n"); strings.TrimSpace(x) != "" {
		w("\n-- BEGIN extra_lua (verbatim from the profile)\n%s\n-- END extra_lua\n", x)
	}
	files[FileConf] = []byte(c.String())
	return files, nil
}

// latencyPolicy is whashed (same name → same upstream, for upstream cache locality) with
// each up server's weight scaled by fastest/own latency, recomputed once a second per
// thread (and at once when the picked server went down since). Latencies below the floor (µs, the format argument) count as equal. Every up
// server keeps weight ≥ 1 so its latency keeps being measured and it can win traffic back.
// Returning n (the server count) means "none available" (dnsdist ≥ 1.9.2).
const latencyPolicy = `setServerPolicyLuaFFIPerThread("whashedLatency", [[
  local ffi = require("ffi")
  local C = ffi.C
  local floor = %d
  local srv = ffi.new("const dnsdist_ffi_server_t*[1]")
  local cum, total, stamp, count = {}, 0, -1, -1
  local function recompute(list, n)
    local best, lat, w = math.huge, {}, {}
    for i = 0, n - 1 do
      C.dnsdist_ffi_servers_list_get_server(list, i, srv)
      if C.dnsdist_ffi_server_is_up(srv[0]) then
        lat[i] = math.max(C.dnsdist_ffi_server_get_latency(srv[0]), floor)
        w[i] = C.dnsdist_ffi_server_get_weight(srv[0])
        best = math.min(best, lat[i])
      end
    end
    total = 0
    for i = 0, n - 1 do
      if lat[i] then total = total + math.max(1, math.floor(w[i] * best / lat[i] + 0.5)) end
      cum[i] = total
    end
  end
  return function(list, dq)
    local n = tonumber(C.dnsdist_ffi_servers_list_get_count(list))
    local now = os.time()
    if now ~= stamp or n ~= count then
      stamp, count = now, n
      recompute(list, n)
    end
    if total == 0 then return n end
    for _ = 1, 2 do
      local h = tonumber(C.dnsdist_ffi_dnsquestion_get_qname_hash(dq, 0) %% total)
      for i = 0, n - 1 do
        if h < cum[i] then
          C.dnsdist_ffi_servers_list_get_server(list, i, srv)
          if C.dnsdist_ffi_server_is_up(srv[0]) then return i end
          break
        end
      end
      recompute(list, n) -- a server went down since the last recompute
      if total == 0 then return n end
    end
    return n
  end
]])
`

// hashCredential returns dnsdist's scrypt format for a webserver password or API key, so
// the plaintext never lands in dnsdist.conf (it stays in the agent's secrets.json). The
// salt is derived from the secret, keeping the render deterministic: a random salt would
// change dnsdist.conf, and so restart dnsdist, on every apply. N/r/p are dnsdist's
// hashPassword() defaults. Already-hashed values (adopted configs) pass through.
func hashCredential(secret string) string {
	if strings.HasPrefix(secret, "$scrypt$") {
		return secret
	}
	sum := sha256.Sum256([]byte("dnsjos webserver credential salt\x00" + secret))
	salt := sum[:16]
	key, err := scrypt.Key([]byte(secret), salt, 1024, 8, 1, 32)
	if err != nil {
		panic(err) // only for invalid N/r/p, which are constants
	}
	b64 := base64.StdEncoding.EncodeToString
	return "$scrypt$ln=10,p=1,r=8$" + b64(salt) + "$" + b64(key)
}

func withDefaults(rt api.NodeRuntime) api.NodeRuntime {
	def := func(s *string, v string) {
		if *s == "" {
			*s = v
		}
	}
	def(&rt.BaseDir, DefaultBaseDir)
	def(&rt.CDBPath, DefaultCDBPath)
	def(&rt.DnstapAddr, DefaultDnstapAddr)
	def(&rt.Hostname, "dnsjos")
	rt.BaseDir = path.Clean(rt.BaseDir)
	return rt
}

// luaString quotes s as a Lua 5.1 string literal. Every byte outside printable ASCII
// becomes a 3-digit decimal escape, so no input can break out of the literal.
func luaString(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch ch := s[i]; {
		case ch == '"' || ch == '\\':
			b.WriteByte('\\')
			b.WriteByte(ch)
		case ch >= 0x20 && ch < 0x7f:
			b.WriteByte(ch)
		default:
			fmt.Fprintf(&b, "\\%03d", ch)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func luaList(items []string) string {
	q := make([]string, len(items))
	for i, s := range items {
		q[i] = luaString(s)
	}
	return "{" + strings.Join(q, ", ") + "}"
}

// addrPort normalises "ip:port" ("[::]:53" style for IPv6).
func addrPort(s string) (string, error) {
	ap, err := netip.ParseAddrPort(s)
	if err != nil || ap.Addr().Zone() != "" {
		return "", fmt.Errorf("%q is not ip:port", s)
	}
	return ap.String(), nil
}

// prefixes normalises CIDRs (host bits cleared); a bare address becomes /32 or /128.
func prefixes(list []string) ([]string, error) {
	out := make([]string, 0, len(list))
	for _, s := range list {
		p, err := netip.ParsePrefix(s)
		if err != nil {
			a, aerr := netip.ParseAddr(s)
			if aerr != nil || a.Zone() != "" {
				return nil, fmt.Errorf("%q is not a CIDR", s)
			}
			p = netip.PrefixFrom(a, a.BitLen())
		}
		out = append(out, p.Masked().String())
	}
	return out, nil
}

// dnsWire encodes a domain name in DNS wire format ("." is the root).
func dnsWire(name string) ([]byte, error) {
	name = strings.TrimSuffix(name, ".")
	var b []byte
	if name != "" {
		for _, l := range strings.Split(name, ".") {
			if l == "" || len(l) > 63 {
				return nil, fmt.Errorf("%q is not a domain name", name)
			}
			b = append(b, byte(len(l)))
			b = append(b, l...)
		}
	}
	if b = append(b, 0); len(b) > 255 {
		return nil, fmt.Errorf("%q is too long", name)
	}
	return b, nil
}

// soaWire encodes "mname rname serial refresh retry expire minimum" as SOA rdata.
func soaWire(soa string) ([]byte, error) {
	f := strings.Fields(soa)
	if len(f) != 7 {
		return nil, errors.New("blocking.soa: must be 'mname rname serial refresh retry expire minimum'")
	}
	var out []byte
	for _, n := range f[:2] {
		w, err := dnsWire(n)
		if err != nil {
			return nil, fmt.Errorf("blocking.soa: %w", err)
		}
		out = append(out, w...)
	}
	for _, n := range f[2:] {
		v, err := strconv.ParseUint(n, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("blocking.soa: %q is not a 32-bit number", n)
		}
		out = append(out, byte(v>>24), byte(v>>16), byte(v>>8), byte(v))
	}
	return out, nil
}

var secretRe = regexp.MustCompile(`((?:setKey\(|password = |apiKey = ))"(?:[^"\\]|\\.)*"`)

// Mask replaces the console key, webserver password and API key with asterisks.
const Mask = `"********"`

// MaskSecrets returns the files as text with every node secret masked (UI previews).
func MaskSecrets(files map[string][]byte) map[string]string {
	out := make(map[string]string, len(files))
	for k, v := range files {
		out[k] = secretRe.ReplaceAllString(string(v), "${1}"+Mask)
	}
	return out
}
